version: "3.8"

services:
  app:
    image: zabop/express-app:latest
    ports:
      - 8080:8080
  watchtower:
    image: containrrr/watchtower
    environment:
      - WATCHTOWER_POLL_INTERVAL=30 # Poll every 30 seconds
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /Users/palszabo/.docker/config.json:/config.json
    container_name: watchtower
